nodiff/README.md, nodiff/action.yaml
This encapsulates our logic that checks whether some auto-formatting tool (that we expect to have no differences) has any differences.
=> Add a "nodiff" action.

.github/workflows/actionlint.yaml
Tweak action to run lint on all yaml files.
mirrors https://github.com/knative/actions/commit/5ed5e1fa5ae4af2da1459e70fca5408939f72f04
=> run action lint on all yaml files.

setup-chainctl/README.md, setup-chainctl/action.yaml
Actions doesn't like the composite workflow accessing secrets.
=> Plumb the invite code through from the caller

kind-diag/action.yaml
Otherwise running this step in a matrix job will overwrite and lose logs
=> Update kind-diag - customize artifact name

kind-diag/action.yaml
In my kind clusters I have auditing turned on and this change reduces file sizes from 1G => 60mb
Some things to note from: https://github.com/actions/upload-artifact#zipped-artifact-downloads
> During a workflow run, files are uploaded and downloaded individually using the upload-artifact and download-artifact actions. However, when a workflow run finishes and an artifact is downloaded from either the UI or through the [download api](https://developer.github.com/v3/actions/artifacts/#download-an-artifact), a zip is dynamically created with all the file contents that were uploaded. There is currently no way to download artifacts after a workflow run finishes in a format other than a zip or to download artifact contents individually. One of the consequences of this limitation is that if a …
=> compress kind logs

setup-melange/action.yaml
This installs melange into a Ubuntu environment with an apk that is suitable for Melange to use to build environments.
=> add setup-melange action

setup-melange/action.yaml
Use () to capture the heredoc so bash doesn't error.
=> setup-melange: fix /etc/apk/repositories generation

melange-build/action.yaml
=> melange-build: fix signing-key-path to use github.workspace

apko-build/action.yaml
These are needed for customizing apko behavior at image build time.
=> apko-build: add archs and keyring-append options

setup-monitoring/README.md, setup-monitoring/action.yaml, setup-monitoring/values.yaml
- Add setup monitoring
That will deploy the Prometheus stack together with Grafana and setup the render backend to we be able to export the Grafana dashboards as images
Sample run: https://github.com/cpanato/testing-ci-providers/runs/6007181409?check_suite_focus=true
=> add action to setup monitoring stack

digesta-bot/action.yml
- remove branch suffix to use the same PR if there is one opened
=> remove branch suffix to use the same PR if there is one opened

kind-diag/action.yaml
Sometimes we see this fail (and stop the subsequent dumps!) when resources are cleaned up between the list/describe.
=> Don't fail on describe

melange-build-pkg/action.yaml, melange-build/action.yaml, melange-index/action.yaml
This splits up the `melange-build` pipeline into multiple composable actions.  That allows for more complex pipelines to be built (like building multiple packages in a CI run).
This will be used to support bootstrapping our Linux distribution.
=> refactor the melange actions

melange-build-pkg/action.yaml, melange-build/action.yaml
Needed to deal with `${{ github.workspace }}` among other things.
=> melange actions: add repository-append and keyring-append inputs

melange-keygen/action.yaml
Allows package building to be simplified slightly.
=> melange-keygen: use github workspace path for key storage

melange-build-pkg/action.yaml
These are helpful for building multiple packages in a single GHA run.
=> melange-build: add workspace-dir option and update-index option

digesta-bot/action.yml
from the job
```
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/mono/mono/setup-gitsign'. Did you forget to run actions/checkout before running your local action?
```
=> we dont checkout the actions repo, so we need to use as a common action

setup-gitsign/action.yml
=> bump gitsign action to use 0.1.0

setup-melange/action.yaml
Fetching the `apk-tools` latest package from edge is fragile.  Switch to using nightly instead.
=> setup-melange: use apk-tools nightly

setup-kind/action.yaml
* Add support for k8s version 1.24.
* Make 1.22 the default instead of 1.21.
* Update all kind images to latest versions.
* Update kind to 0.14.0
=> Add k8s version 1.24 as an option, update others to latest. Update kind to 0.14.0

setup-knative/action.yaml
* Bump Knative default to 1.5.0
* Note that v1.4.0 required k8s v1.22 so also made the default in #94 for k8s be 1.22 so that defaults provide a supported system.
=> Use latest knative (1.5.0) by default.

kind-diag/action.yaml
This may happen when resource installation hasn't completed or clean up failed midway.
=> Don't fail if the resource definition disappears

melange-build-pkg/action.yaml
melange/apko currently need root, otherwise you get this error:
```
Error: failed to build package: unable to build workspace: unable to generate image: failed to mutate accounts: chown(0, 0) = chown /tmp/melange-guest-2288225804/root: operation not permitted
```
=> [melange-build-pkg]: run 'melange build' with sudo

melange-build-pkg/action.yaml
right now, we are using sudo to invoke melange because
melange is performing some privileged operations
so we need to fix the permissions of the repo that we
generate, otherwise it winds up owned as root
=> melange-build-pkg: fix repo permissions

.gitignore, githubapp-token/README.md, githubapp-token/action.yaml
This is helpful when impersonating a GitHub App to complete tasks, such as automated PRs or deploying to a environment branch.
=> New action to generate token as a GitHub App

melange-build/action.yaml
Signing the index multiple times can result in the wrong checksum for the signature payload.
=> melange-build: do not call melange-build-pkg with update-index:true

setup-registry/action.yaml
Without this, the lines are combined to form
```
go install github.com/google/go-containerregistry/cmd/registry@main registry --port=${{inputs.path}}
```
which `go install` doesn't like very much at all.
=> fix bug in setup-registry

setup-mirror/action.yaml
Some Ubuntu Actions images don't have an `/etc/docker/daemon.json` configuration and setup-mirror assumes this file exists. This change creates an empty file config (e.g `{}`) if none already exists.
=> setup-mirror: Don't assume docker daemon config exists

setup-hakn/README.md, setup-hakn/action.yaml, setup-knative-eventing/README.md, setup-knative-eventing/action.yaml
We are switching most of our test workflows to use `setup-hakn` + `setup-knative-eventing` instead of `setup-knative`.
Most code for `setup-knative-eventing` comes from `setup-knative` with all the serving parts stripped out. 
The plan is that, in follow up PRs:
(a) after all workflows switch over, we will delete `setup-knative`
(b) after github.com/chainguard-dev/hakn acquires Knative Eventing capacity, we will delete `setup-knative-eventing` as well and only use `setup-hakn`.
=> Add setup-hakn and setup-knative-eventing to replace setup-knative

setup-gitsign/action.yml
Noticed an issue where the checksum failed, but didn't really say why:
```
INFO: Downloading gitsign version 'v0.1.1' from https://github.com/sigstore/gitsign/releases/download/v0.1.1/gitsign_0.1.1_linux_amd64
ERROR: Unable to validate gitsign version: 'v0.1.1'
Error: Process completed with exit code 1.
```
I suspect this was really caused by an issue fetching the file from GitHub, but this just adds a bit more info so we can try and see what happened if things fail.
=> setup-gitsign: log got/want checksum SHAs.

setup-hakn/action.yaml
This makes API server traffic completely bypass Istio sidecar. Hopefully will help with flakes where sidecar server starts later than when a Pod needs to talk to API server.
See https://istio.io/latest/docs/tasks/traffic-management/egress/egress-control/#direct-access-to-external-services.
=> Exclude the K8s API server from Istio egress

digesta-bot/action.yml
Skip testdata that might cause digesta-bot to fail
```
Image ghcr.io/user-a/alpine-base in file /home/runner/work/mono/mono/api-impl/fake/testdata/records.yaml does not have a tag, ignoring...
Image ghcr.io/user-b/apko in file /home/runner/work/mono/mono/api-impl/fake/testdata/records.yaml does not have a tag, ignoring...
Image registry.test/contexts-testing/apko in file /home/runner/work/mono/mono/api-impl/fake/testdata/records.yaml does not have a tag, ignoring...
Processing pkg:oci/static in file /home/runner/work/mono/mono/api-impl/fake/testdata/records.yaml
2022/08/13 01:30:34 HEAD request failed, falling back on GET: could not parse reference: pkg:oci/static
Error: parsing reference "pkg:oci/static": could not parse reference: pkg:oci/static
Error: Process completed with exit code …
```
=> skip testdata for digestabot

digesta-bot/action.yml
Skipping local registry that digestabot cant process
```
Processing registry.local:5000/policy-controller/demo in file /home/runner/work/mono/mono/.github/workflows/agentless-kind.yaml
2022/08/15 16:02:22 HEAD request failed, falling back on GET: Get "https://registry.local:5000/v2/": dial tcp: lookup registry.local on 127.0.0.53:53: server misbehaving; Get "http://registry.local:5000/v2/": dial tcp: lookup registry.local on 127.0.0.53:53: server misbehaving
Error: Get "https://registry.local:5000/v2/": dial tcp: lookup registry.local on 127.0.0.53:53: server misbehaving; Get "http://registry.local:5000/v2/": dial tcp: lookup registry.local on 127.0.0.53:53: server misbehaving
Error: Process completed with exit code 1.
```
=> skip local registry for digestabot

release-notes/README.md, release-notes/action.yml
as part of the release-notes automation, this adds the action that will be in charge to generate/update the release-notes
as soon we merge this will do the job in the mono repo
=> add release-notes action

inky-build-pkg/action.yaml
Improve the `inky-build-pkg` action to allow the key name to be configurable.
=> inky-build-pkg: allow key name to be configurable

setup-spdx/README.md, setup-spdx/action.yaml
This PR introduces a new reusable action based on the [`ko` SBOM verification action](https://github.com/google/ko/blob/main/.github/workflows/sbom.yaml) that installs the SPDX java tools jar and optionally checks an SBOM to ensure its syntax is valid.
This action will allow us to verify all SPDX SBOMs we produce in apko ([see here an initial use in `bom`](https://github.com/puerco/bom/blob/check-action/.github/workflows/verify-spdx.yaml)).
=> SPDX Tools Setup and SBOM validation action

inky-build-pkg/action.yaml
xref chainguard-dev/internal#667
=> inky-build-pkg: change default signing key name to wolfi-signing.rsa

setup-chainctl/action.yaml
We hit a problem where trying to expand the capabilities of our actions runner didn't work because we weren't even trying to accept the invite code, and proceeded with inadequate capabilities.
This makes it so that we always try to do an idempotent invite code acceptance.
=> Always attempt to accept an invite code when specified.

inky-build-pkg/README.md, wolfi-build-pkg/action.yaml
- add wolfi-build-pkg and deprecate inky-build-pkg
this will be a 2 step change, first we duplicate the action, then replace where we use and in the end we remove the old action
=> add wolfi-build-pkg and deprecate inky-build-pkg

setup-hakn/README.md, setup-hakn/action.yaml
=> bump setup-hakn default to 1.7.0

setup-kind/action.yaml
As per:
https://github.com/kubernetes-sigs/kind/releases
=> kind default to v0.15.0. Add k8s 1.25, update images

.github/workflows/test-setup-kind.yaml, setup-kind/action.yaml
Previous of version was soooo old that so many things had changed, including how one defines the addresspools. So instead of using configmap, switch to using CRD.
Also add a test that spins up Knative to make sure cluster is functional.
=> change metallb addresspool to use CRD vs. configmap.

.github/workflows/test-setup-kind.yaml, setup-knative/action.yaml
Knative version v1.7.x is little wonky and some components were released with v1.7.1 and some with v1.7.0 and some don't have v1.7.1 or they have a release that doesn't work at v.1.7.0, so we can not use a single version to install. To unblock the testing with v1.25 of k8s, introduce a 'latest' keyword that will fetch the latest release for each component.
=> add 'latest' keyword that will install mismatching versions of latest. Test with k8s v1.25.x

inky-build-pkg/action.yaml
This makes it a lot easier to just add security patches as needed to packages.
=> inky-build-pkg: normalize source-directory and drop empty-workspace

inky-build-pkg/action.yaml
Why github actions doesn't just default to `bash`, the world will probably never know...
=> inky-build-pkg: use bash shell when creating optional patches directory

.github/workflows/actionlint.yaml
- Use GITHUB_OUTPUT instead of deprecated set-output
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Use GITHUB_OUTPUT instead of deprecated set-output

setup-kind/action.yaml
With this change we were seeing `sigstore/scaffolding` failing to start Fulcio with:
```
error loading --config-path=/etc/fulcio-config/config.json: provider https://kubernetes.default.svc.cluster.local/: oidc: issuer did not match the issuer returned by provider, expected "https://kubernetes.default.svc.cluster.local/" got "https://kubernetes.default.svc/"
```
This is concerning because the patch block is specifically requesting the issuer without `.cluster.local`.  Reverting this until we can sort out the reason for the behavior change.
cc @dprotaso @vaikas
=> Partially revert #173

boilerplate/action.yaml
Updates boilerplate check to work with go 1.19.
Tested against the UI repo: https://github.com/chainguard-dev/console-ui/actions/runs/3660259108/jobs/6187205572
=> Fix: boilerplate for go 1.19

gofmt/action.yaml, goimports/action.yaml
This tweaks the find command to not have a hard depth limit of 3, and instead uses a -prune to limit the directories it will traverse down.
=> [gofmt/goimport] Don't limit find depth to 3.

setup-hakn/action.yaml
cleanup: bump hakn default to 1.8.5 from 1.8.0
=> cleanup: bump hakn default to 1.8.5 from 1.8.0

setup-chainctl/README.md, setup-chainctl/action.yaml
Also use `https://dl.enforce.dev` instead of GCS.
=> setup-chainctl: provide defaults for env and audience

.github/workflows/test-setup.yaml, setup-chainctl/README.md, setup-chainctl/action.yaml, setup-chainguard-terraform/README.md, setup-chainguard-terraform/action.yaml
Also add some basic tests that setup-chainctl and setup-chainguard-terraform can successfully install without params.
=> update setup-chainguard-terraform to match setup-chainctl changes

setup-spdx/action.yaml
Update the jar file to the last version of the SPDX java tools in the SPDX action
Signed-off-by: Adolfo García Veytia (Puerco) <puerco@chainguard.dev>
=> setup-spdx: Bump spdx/tools-java to 1.1.3

setup-melange/action.yaml
If using in a repo containing a `melange/` dir, bad stuff happens
=> Allow setup-melange to work when a melange/ directory already exists

setup-chainctl/README.md, setup-chainctl/action.yaml
:gift: This change deprecates the invite code path in favor of a new path leveraging assumed identities.
I used this here to assume an identity I provisioned against staging, and push to a repository is has access to...
https://github.com/mattmoor/chainguard-registry-test/actions/runs/4131040944/jobs/7138381933#step:6:21
I believe it's harmless to add the `configure-docker` piece even though we don't actually have a production registry (yet), especially since this is on a new path via `identity:`, so YOLO...
/kind feature
=> Feature: Switch `setup-chainctl` to prefer identities.

setup-chainguard-terraform/README.md, setup-chainguard-terraform/action.yaml
:gift: This plumbs the new identity stuff through the `setup-chainguard-terraform` actions.
/kind feature
=> Feature: Deprecate the invite-code path, add identity support

.github/workflows/test-setup-kind.yaml, setup-kind/action.yaml
The KinD latest release has the 1.27.x support https://github.com/kubernetes-sigs/kind/releases/tag/v0.18.0
So this patch changes:
- bumps KinD version to v0.18.0.
- adds k8s 1.27.x support.
=> Add k8s 1.27.x support for setup-kind/action.yaml

eof-newline/action.yaml
Sometimes testdata needs to have no newlines - e.g. if we're comparing data against a signature, adding a new line would invalidate existing signatures.
=> eof-newline: Ignore testdata directories.

digesta-bot/action.yml
use case:
```
- op: replace
path: /spec/template/spec/containers/0/args/3
value: --acme-http01-solver-image=cgr.dev/chainguard/cert-manager-acmesolver:1.11.1@sha256:059c0b906e1f0f031e8a4a55d43e193d6b1e75e99f8eb9ae406ecdea7c99ec42
```
need to remove anything before `=`
Fixes: https://github.com/chainguard-dev/mono/issues/10123
=> fix digesta bot

.github/workflows/test-setup-registry.yaml, setup-registry/action.yaml
Using `setup-crane` means the latest release of the registry will be used, and the user doesn't have to have Go available to `go install` from source. This will be harder to mess up, and quite a bit faster as a bonus.
If we want to retain the old from-head behavior, we can add a parameter for `version` with the same semantics as `setup-crane`, with `default` meaning the latest release, and `tip` meaning `go install @main`, and other released versions available. I don't think anybody depends on this today though.
`crane registry serve` also has the ability to choose a random available port if one is not specified. This could be useful, but we'd want a way for `crane registry serve` and `setup-registry` to output the chosen port so subsequent steps can interact with the registry. For now, …
=> setup-registry: use crane registry serve

eof-newline/action.yaml
The test is failing ambiguously, so dump out the reviewdog input for more details.
See https://github.com/chainguard-dev/mono/actions/runs/4983299872/jobs/8920138260?pr=10102 for example failure.
=> eof-newline: Dump reviewdog input to stderr.

trailing-space/action.yaml
I'm pretty sure the input to reviewdog is also busted, but idk what the format is. Added additional logging to output what is being fed to reviewdog to stderr.
=> trailing-space: ignore testdata

setup-chainctl/action.yaml
Before this change:
```
--2023-06-01 14:16:08--  https://dl.enforce.dev/chainctl/latest/chainctl_linux_x86_64
Resolving dl.enforce.dev (dl.enforce.dev)... 34.[117](https://github.com/chainguard-images/images/actions/runs/5145433910/jobs/9263121546#step:5:129).0.114
Connecting to dl.enforce.dev (dl.enforce.dev)|34.117.0.114|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 57966592 (55M) [application/octet-stream]
Saving to: ‘chainctl’
0K .......... .......... .......... .......... ..........  0% 24.8M 2s
50K .......... .......... .......... .......... ..........  0% 47.5M 2s
100K .......... .......... .......... .......... ..........  0% 50.4M 1s
150K .......... .......... .......... .......... ..........  0% 90.3M 1s
200K .......... .......... .......... …
```
=> Silence spammy wget logs

setup-chainctl/action.yaml
Previously our action required sudo to move the chainctl binary to `/usr/local/bin`. Moving it to `~/.local/bin` does not require sudo. I suspect the original action breaks on self-hosted runners, setting some up now to test and confirm
=> Setup chainctl remove the need for sudo

setup-kind/action.yaml
* contains a fix for a cgroup mount used by Kind on Github actions that causes failures
* https://github.com/kubernetes-sigs/kind/releases/tag/v0.20.0
=> bump to kind 0.20.0

setup-kind/README.md
Alternatively we could strip the `v` prefix from both if they're provided, so this is less confusing.
=> Update setup-kind README

.github/workflows/test-setup-kind.yaml, setup-kind/README.md, setup-kind/action.yaml
follow up of https://github.com/chainguard-dev/actions/pull/255
=> remove v from the k8s-version to match the others and update docs

githubapp-token/action.yaml
The latest version of @octokit/app dropped support for Node v16: https://github.com/octokit/app.js/releases/tag/v14.0.0
=> Fix: GitHub App action

boilerplate/action.yaml
This should disable the `Warning: Restore cache failed: Dependencies file is not found` warning message in action logs.
=> boilerplate: disable caching for setup-go

.github/workflows/test-setup-kind.yaml, setup-kind/action.yaml
We are facing many issues due to a change in the fulcio configuration for the kubernetes issuer, this creates a mismatch to what the kubernetes cluster sets and what the oidc issuer expects.
Therefore I believe we need this new parameter to adapt the want/got expectations.
=> setup-kind: Add a new parameter to define the service account issuer

setup-gitsign/action.yml
The binary used for ARM64 was `amd64`. 🚨
=> Fix gitsign binary name on OSX/ARM64

digesta-bot/action.yml
- don't fail the job if cannot get the digest for a specific image but instead log that error
also add an option to skip PR creation.
the errors will be reported in the in the job summary, ie see below
=> dont fail the job if cannot get the digest for a specific image but instead log that error

k8s-diag/action.yaml
This PR introduces 2 new diagnostics steps for Kubernetes cluster:
* Pod Logs by Namespece
* Events by Namespece
I could add `events` to `inputs.cluster-resources` make it would resulting non-easy UX. By using `get events`, we can able to pass some _filters_ and _sorting_ options. It would provide easy debugging.
=> k8s-diag: add pod logs and cluster events

setup-kind/action.yaml
- Adding Kindest image reference for version 1.28.x
- Image SHA from: https://github.com/kubernetes-sigs/kind/releases/tag/v0.20.0
=> add kindest image for version 1.28.x

setup-k3d/action.yaml
This defaults to `https://kubernetes.default.svc.cluster.local` which causes problems trying to stand up sigstore scaffolding.
=> Switch to https://kubernetes.default.svc for k3s issuer.

setup-kind/action.yaml
Fixes #307 
Allows users to specify `kind-worker-count: 0` and create a kind cluster with only a single node.
=> Allow creating single-node kind cluster

setup-kind/action.yaml
Currently broken, see https://github.com/chainguard-dev/actions/pull/335
=> setup-kind: fix indented heredoc end-marker

setup-gcsfuse/README.md, setup-gcsfuse/action.yaml
we tend to just use `apk add gcsfuse`, but this installs gcsfuse for environments/runners not hooked up with `apk`.
=> add setup-gcsfuse action

setup-kind/action.yaml
We want to use kubernetes version 1.29.x in https://github.com/sigstore/scaffolding, but that action uses chainguard's setup-kind action which does not support kubernetes version v1.29.
This PR adds support for kubernetes version 1.29.
cc @wlynch @mattmoor @cpanato
=> chore: add support for 1.29.x in setup-kind

githubapp-token/action.yaml
This updates the script to ensure the `npm install` command doesn't interface with a `package.json` found in the root of the workspace.
=> githubapp-token: Bump dependencies, add global install

octo-sts/README.md, octo-sts/action.yaml
An example of it working with `gh` CLI:
An example failure:
Fixes: https://github.com/chainguard-dev/octo-sts/issues/5
=> Add an action for federating for octo-sts tokens

k8s-diag/action.yaml, kind-diag/action.yaml, nodiff/action.yaml, release-notes/action.yml, setup-spdx/README.md
v3 ones are deprecated, use obsolete node and will break in Autumn
2024. v4 ones are compatible and faster.
This should remove lots of warnings in all the actions.
Signed-off-by: Dimitri John Ledkov <dimitri.ledkov@chainguard.dev>
=> upgrade arifact actions to v4

setup-chainctl/README.md, setup-chainguard-terraform/README.md, setup-chainguard-terraform/action.yaml
`setup-chainguard-terraform` simply calls out to `chainguard-dev/setup-chainctl`. Deprecate this action in favor of `setup-chainctl`.
=> add deprecation warning to `setup-chainguard-terraform`

setup-gitsign/action.yml
While working on #442, I noticed that Gitsign was still pinned to `0.8.0` with the latest version being `0.10.2`; this PR updates Gitsign.
New SHAs for reference:
```
gitsign_0.10.2_darwin_amd64 5efdf5541d3698f32b60bdfc3f9dfca8d3bff5960b69b95081b72e88c23cc02f
gitsign_0.10.2_darwin_arm64 e8f31efc33c74484f56e2ee8cc889fe4eafd66da150ab53e2438b03c4be548a4
gitsign_0.10.2_linux_amd64 f9dfe821d0456f11de444de4d90ccd64d7797b5992161f3318b9bf85871c8f78
gitsign_0.10.2_linux_arm64 f65cca3498038e76f089ec473f9bdce83bf7e2aa15bbdc147b5b222aa0287ceb
gitsign_0.10.2_windows_amd64.exe c14f4cd67becb7e6937a1a8c363c88468cabaae959401b80e5340ad6fde5cbcc
gitsign_0.10.2_windows_arm64.exe b86113bb9a14a4446bb0758cd35d9708907ff2037e816ec838f2caf75c3d342c
```
=> Bump Gitsign to 0.10.2

.github/workflows/actionlint.yaml
by default it ANDs the name flags, so it only matched one file previously
change it to match any *.yaml or *.yml file
=> fix find for actionlint workflow

melange-build-pkg/action.yaml, melange-build/action.yaml
Allows providing the URL of the git repository and the commit SHA containing the build config file.
Needed due to this change: https://github.com/chainguard-dev/melange/commit/eab3401f8019e134af6fe070e4d4bcff57993d30
=> Add git repo URL and commit SHA parameters

melange-build/action.yaml
Allow for a specific version of `melange` to be used when running the `melange-build` action. Default value is `latest-release` (following what is used in the setup-melange action) so this is expected to be backward compatible.
=> feat(melange-build): allow for specific melange version

setup-gitsign/action.yml
It's been a while since `gitsign` `0.10.2` was released -- `0.11.0` released 11/04 so I wanted to make sure it made its way into the action.
=> Update setup-gitsign to 0.11.0

.github/workflows/actionlint.yaml
The action was pointing to the v1 tag, so pinned to the current commit and also added a comment for the specific version tag associated with it, so that dependabot can keep it up to date.
The v1.65.0 tag is confirmed to be the same commit as the v1 tag:
```
$ git ls-remote https://github.com/reviewdog/action-actionlint | grep db58217885f9a6570da9c71be4e40ec33fe44a1f
db58217885f9a6570da9c71be4e40ec33fe44a1f        refs/heads/releases/v1
db58217885f9a6570da9c71be4e40ec33fe44a1f        refs/tags/v1^{}
db58217885f9a6570da9c71be4e40ec33fe44a1f        refs/tags/v1.65^{}
db58217885f9a6570da9c71be4e40ec33fe44a1f        refs/tags/v1.65.0^{}
```
or see https://github.com/reviewdog/action-actionlint/tags directly
I have also verified that the same commit was used in the most recent github action …
=> pin reviewdog/action-actionlint to specific commit

boilerplate/action.yaml
```
time=2025-03-20T08:17:55.486Z level=WARN msg="reviewdog: -fail-on-error is deprecated. Use -fail-level=any, or -fail-level=error for github-[pr-]check reporter instead. See also https://github.com/reviewdog/reviewdog/blob/master/CHANGELOG.md"
```
=> update deprecated flag

hugo2confluence/.gitignore, hugo2confluence/README.md, hugo2confluence/action.yaml, hugo2confluence/go.mod, hugo2confluence/go.sum, hugo2confluence/label/label.go, hugo2confluence/main.go
uses my fork with changes in https://github.com/Virtomize/confluence-go-api/pull/69 in order to allow paged searches
=> hugo2confluence: auto cleanup pages removed in hugo

.github/workflows/test-gitsign.yaml, setup-gitsign/action.yml
This PR updates gitsign from `0.11.0` to `0.13.0`.
I also added coverage for linux-arm64 and darwin-amd64. GitHub doesn't offer windows-arm64 Runners yet, so that's the one gap we can't cover easily.
=> Update gitsign to 0.13.0

.github/workflows/test-gitsign.yaml, setup-gitsign/action.yml
We can now test installation coverage across all three Mac/Linux/Windows architecture pairs: https://github.blog/changelog/2025-04-14-windows-arm64-hosted-runners-now-available-in-public-preview/
=> Add new ARM64 Windows Runner to Gitsign matrix

setup-gitsign/action.yml
FYI: gitsign can now also verify a tag signed by gitsign. https://github.com/sigstore/gitsign/pull/659
=> Add tag signing configuration to setup-gitsign action

.github/chainguard/release.sts.yaml, .github/workflows/actionlint.yaml, .github/workflows/release.yaml, .goreleaser.yml
The idea here is to run a release every week if we have changes in the repository; then it will tag and create a new GH release, and with that, we then can pin the chainguard-dev/actions to a tagged hash :)
=> Add release job 

.github/workflows/release.yaml
Any forks of this repository will have this workflow attempt to run. It will fail because it does not have credentials to run.
Error looks like this:
Error: no installation found for "smoser"
=> Only run release workflow from chainguard-dev/actions

.github/workflows/test-apt-faster.yaml, .github/workflows/test-setup-eksctl.yaml, .github/workflows/test-setup-kind.yaml, .github/workflows/test-setup-melange.yaml, .github/workflows/test-setup-registry.yaml
These workflows were not getting triggered on pull requests that changed the expected files.
I believe that was because of a leading './' in the paths.
So, remove the leading './'.
=> Fixup on.pull_request.paths conditions in workflows.
