chainguard-dev/actions

goimports/action.yaml
Oops: https://github.com/sigstore/cosign/runs/5279307331?check_suite_focus=true#step:1:34
=> Add missing shell directive

setup-knative/README.md, setup-knative/action.yaml
These must be complete for the Github download URL.  Oops.
=> Fix Knative version strings.

eof-newline/README.md, eof-newline/action.yaml, nodiff/README.md, nodiff/action.yaml, trailing-space/README.md, trailing-space/action.yaml
git repo may not be at base github_workspace.
=> allow specifying repo path.

apko-build/README.md, apko-build/action.yaml
Demo here: https://github.com/kaniini/apko-test
=> Support building OCI images with apko.

apko-build/README.md, apko-build/action.yaml
Caveat: I still need to try this 😅
=> Add a digest output to apko-build

setup-melange/action.yaml
Forgot to add bubblewrap dependency, oops.
=> setup-melange: add bubblewrap dependency

melange-build/action.yaml, melange-keygen/action.yaml, setup-melange/action.yaml
Slightly different semantics for `act` verses real github actions...
=> melange actions: use sudo and proot when appropriate

setup-kind/action.yaml
- add kind-start-time output
xref: https://github.com/chainguard-dev/mono/pull/1172
=> add kind-start-time output

update-digest/README.md, update-digest/action.yml
- add initial action to update the image digest
sample run: https://github.com/cpanato/testing-ci-providers/pull/73 and action run https://github.com/cpanato/testing-ci-providers/runs/6022569532?check_suite_focus=true
=> add initial action to update the image digest

setup-monitoring/values.yaml
fixing some issues found while running the action for this PR https://github.com/chainguard-dev/mono/pull/1283
=> fixes for setup-monitoring

digesta-bot/README.md, digesta-bot/action.yml
update action name and check if the image have a tag otherwise ignore the update
=> update action name and check if image have a tag otherwise ignore the update

setup-knative/action.yaml
=> Add an output for the Knative LB IP.

setup-registry/README.md, setup-registry/action.yaml
cc @amouat since we were talking about this
=> Add setup-registry to install and run ggcr's cmd/registry

apko-build/action.yaml, setup-knative/action.yaml
See https://github.com/distroless/actions/pull/11
Needs to wait for an apko release (v0.4.0)
=> Add support for new --use-docker-mediatypes flag

kind-diag/action.yaml
=> do not hang forever when grafana is not available

boilerplate/action.yaml, digesta-bot/action.yml, eof-newline/action.yaml, kind-diag/action.yaml, setup-melange/action.yaml, setup-monitoring/action.yaml, setup-registry/action.yaml, trailing-space/action.yaml
=> use git hash instead of tag

setup-registry/action.yaml
Signed-off-by: Priya Wadhwa <priya@chainguard.dev>
=> Run registry in background

digesta-bot/action.yml
- add kind and release notes label
adding those labels to avoid the needed of manual intervention :)
=> add kind and release notes label

release-notes/action.yml
disable dependencies generation for now
=> disable dependencies generation for now

digesta-bot/action.yml
- add markdown for the release notes
=> add markdown for the release notes

.github/workflows/test-setup-kind.yaml, setup-kind/action.yaml
=> Update metallb to latest because PodSecurityPolicy was removed. Add action tests.

setup-kind/README.md, setup-kind/action.yaml
- update kind to v0.16.0 and kind nodes images
cc @vaikas @mattmoor
=> update kind to v0.16.0 and kind nodes images

eof-newline/action.yaml, trailing-space/action.yaml
- ignore licenses directory
needed for https://github.com/sigstore/cosign/pull/2259
=> ignore licenses directory

setup-registry/README.md
Fixes https://github.com/chainguard-dev/actions/issues/159
=> update example image to cgr.dev

release-notes/action.yml
to avoid overlap with existing PRs
=> create a dedicate branch for each executition

release-notes/action.yml
Fixes: https://github.com/chainguard-dev/mono/issues/5157
=> checkout same branch that the release notes will use

setup-knative/action.yaml
=> add option to select use 1.7.x version format

setup-hakn/action.yaml
:gift: Switch us to the distroless tag of istio images.
/king feature
=> Feature: Use the distroless tag of Istio for testing.

setup-hakn/action.yaml, setup-knative-eventing/action.yaml, setup-knative/README.md, setup-knative/action.yaml
- bump knative and hakn to 1.8.0
=> bump knative and hakn to 1.8.0

githubapp-token/action.yaml
Updates setup-node inside the `githubapp-token` action
=> Upgrade to actions/setup-node@v3

melange-build-pkg/action.yaml
Bug introduced in #188 causing failing builds
=> Fix error in melange-build-pkg

melange-build-pkg/action.yaml
Signed-off-by: Josh Dolitsky <josh@dolit.ski>
=> Fix missing quote in melange-build-pkg

.github/dependabot.yml
-add initial config for dependabot
looks like dependabot can update action in a non standard directory, i will test it
=> add initial config for dependabot

setup-chainctl/action.yaml
=> update chainctl download url

setup-gitsign/action.yml
- update gitsign to use release v0.5.2
=> update gitsign to use release v0.5.2

boilerplate/action.yaml, release-notes/action.yml
cleanup: update actions to go 1.20
=> cleanup: update actions to go 1.20

digesta-bot/action.yml
Part of https://github.com/chainguard-dev/mono/issues/9999
=> output the pull request number and update actions

digesta-bot/README.md
Fixes: https://github.com/chainguard-dev/actions/issues/256
=> update docs for digesta-bot

digesta-bot/action.yml
Fixes: https://github.com/chainguard-dev/actions/issues/259
=> add .sh to be included in the digestbot

.github/workflows/test-setup-melange.yaml, setup-melange/action.yaml, setup-melange/example/melange.yaml
Also add tests for setup-melange and melange-build actions
=> Don't install apk to install melange

.github/dependabot.yml, .github/workflows/actionlint.yaml, .github/workflows/test-gitsign.yaml, .github/workflows/test-matrix-extra-inputs.yaml, .github/workflows/test-setup-kind.yaml, .github/workflows/test-setup-melange.yaml, .github/workflows/test-setup-registry.yaml, melange-keygen/action.yaml
- add a few more actions to dependabot config
- only run tests if the specific actions changed
=> Updates on actions

k8s-diag/README.md, k8s-diag/action.yaml, setup-k3d/README.md, setup-k3d/action.yaml
alternative to `setup-kind`, this time with more `k3s` and faster startups
also adds a more generic `k8s-diag` to replace the purpose built `kind-diag`
=> add a setup k3d action

.github/workflows/test-setup-kind.yaml, setup-hakn/README.md, setup-hakn/action.yaml, setup-knative-eventing/README.md, setup-knative-eventing/action.yaml, setup-knative/README.md, setup-knative/action.yaml
update knative related packages to v1.11.0
=> update default versions for knative

setup-gitsign/action.yml
With a single `case` statement decision on OS+arch is much more readable and shorter.
=> Use a single case statement for OS+arch

digesta-bot/action.yml
Initialize variable `updated_digest` otherwise that was with the last value and causing the image to be updated with a wrong digest
=> Initialize variable and change id that was doing conflict

clank/README.md, clank/action.yml
job execution example: https://github.com/cpanato/testing-ci-providers/actions/runs/6305173342/job/17118074953
=> add clank action

.github/workflows/test-setup-kind.yaml, whereami/README.md, whereami/action.yaml
cc @jonjohnsonjr whose idea this was
=> add whereami action

setup-gitsign/action.yml
=> bump gitsign to v0.8.0

nodiff/action.yaml
git diff only looks at files that git is aware of. It does not consider new files that were added.
=> nodiff: Check for untracked files.

setup-melange/action.yaml
This bash was stolen from setup-knative.
=> Install correct os/arch for setup-melange

setup-kind/action.yaml
Drop support for K8s releases that aren't supported
=> Bump Kind Version to v0.22.0

nodiff/action.yaml
=> nodiff: Upload patch file on failure.

setup-kind/README.md, setup-kind/action.yaml
bump kind to v0.23.0 add 1.30 k8s / remove 1.23/24 and updates kindest/node images
=> bump kind to v0.23.0 add 1.30 k8s / remove 1.23/24 and updates kindest/node images

setup-kind/action.yaml
- Fixes https://github.com/chainguard-dev/actions/issues/446
=> Fix docker inspect for latest runner images

boilerplate/README.md
Fix a mistake in the documentation for the boilerplate action.
=> Correct usage example for boilerplate

setup-knative/action.yaml
this is to allow avoiding calls to api.github.com if specific versions are specified
=> allow specifying specific serving/eventing version

hugo2confluence/.gitignore, hugo2confluence/README.md, hugo2confluence/action.yaml, hugo2confluence/cleanup/cleanup.go, hugo2confluence/go.mod, hugo2confluence/go.sum, hugo2confluence/main.go
GitHub Action and Go-based tool to convert and publish a Hugo-based site to Confluence
=> Add hugo2confluence action

hugo2confluence/action.yaml
=> Hotfix for hugo2confluence

hugo2confluence/main.go
=> hugo2confluence: remove commented out delete call

git-tag/action.yml
see https://github.com/cpanato/testing-ci-providers/actions/runs/14470989819/job/40584581984
=> fix git tag

.github/workflows/test-argo-workflows.yaml, setup-argo-workflows/README.md, setup-argo-workflows/action.yaml
Fixes: https://github.com/chainguard-dev/internal-dev/issues/13887
releated to https://github.com/chainguard-dev/internal-dev/issues/12599
=> add setup-argo-workflows

goimports/action.yaml
ref: https://github.com/chainguard-dev/actions/pull/601
=> Ignore testdata in goimports
